services:
  server:
    build:
      context: .
      target: final
    ports:
      - 6969:6969
    depends_on:
      - maria
      - redis

  maria:
    image: mariadb
    container_name: maria
    environment:
      MYSQL_ROOT_PASSWORD: axcelium
    ports:
      - 3306:3306
    networks:
      - mynetwork

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
