services:
  # server:
  #   build:
  #     context: .
  #     target: final
  #   ports:
  #     - 6969:6969
  #   depends_on:
  #     - scylla
  #     - dragonfly
  #   networks:
  #     - mynetwork

  scylla:
    image: scylladb/scylla
    container_name: scylla
    ports:
      - 9042:9042
      - 10000:10000
    volumes:
      - scylla-data:/var/lib/scylla
    networks:
      - mynetwork

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly
    ports:
      - 6379:6379
    command: ["--maxmemory", "3gb"]
    networks:
      - mynetwork

volumes:
  scylla-data:

networks:
  mynetwork:
    driver: bridge
